select nombre from producto;
select nombre,precio from producto;
select * from producto;
select nombre,concat(precio,'€'),concat(round(precio*1.19239,2),'$') from producto;
select nombre as 'nom de producto',concat(precio,'€') as 'euros',concat(round(precio*1.19239,2),'$') as 'dollars' from producto;
select upper(nombre),precio from producto;
select lower(nombre),precio from producto;
select nombre,upper(substring(nombre,1,2)) from fabricante;
select nombre,round(precio) from producto;
select nombre,truncate(precio,0) from producto;
select f.codigo from producto p,fabricante f where f.codigo = p.codigo_fabricante;
select distinct f.codigo from producto p,fabricante f where f.codigo = p.codigo_fabricante;
select nombre from fabricante order by nombre;
select nombre from fabricante order by nombre desc;
select * from fabricante limit 5;
select * from fabricante limit 4,2;
select nombre,precio from producto order by precio asc limit 1;
select nombre,precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select p.nombre as 'producto',p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre as 'producto',p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo order by f.nombre asc;
select p.codigo,p.nombre,f.codigo,f.nombre from producto p,fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo order by p.precio limit 1;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo order by p.precio desc limit 1;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Lenovo';
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Crucial' and p.precio > 200;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and (f.nombre like 'Hewlett-Packard' or f.nombre like 'Seagate' or f.nombre like 'Asus');
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre in('Hewlett-Packard','Seagate','Asus');
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like '%e';
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like '%w%';
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and p.precio > 180 order by p.precio desc, p.nombre asc;
select distinct f.codigo,f.nombre from producto p,fabricante f where f.codigo = p.codigo_fabricante;
select fabricante.nombre as 'fabricante',producto.nombre from producto right outer join fabricante on producto.codigo_fabricante = fabricante.codigo;
--35
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Lenovo';
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre != 'Lenovo' and p.precio = (select p.precio from producto p,fabricante f where f.codigo = p.codigo_fabricante and f.nombre like 'Lenovo' order by p.precio desc limit 1);
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Lenovo' order by p.precio desc limit 1;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Hewlett-Packard' order by p.precio asc limit 1;
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre != 'Lenovo' and p.precio >= (select p.precio from producto p,fabricante f where f.codigo = p.codigo_fabricante and f.nombre like 'Lenovo' order by p.precio desc limit 1);
select p.nombre,p.precio,f.nombre as 'fabricante' from producto p,fabricante f where p.codigo_fabricante = f.codigo and f.nombre like 'Asus' and p.precio > (select AVG(p.precio) from producto p,fabricante f where f.nombre like 'Asus' and p.codigo_fabricante = f.codigo);
