select apellido1,apellido2,nombre from persona where tipo like 'alumno' order by apellido1,apellido2,nombre desc;
select apellido1,apellido2,nombre from persona where tipo like 'alumno' and telefono is null;
select apellido1,apellido2,nombre from persona where tipo like 'alumno' and fecha_nacimiento like '1999%';
select apellido1,apellido2,nombre from persona where tipo like 'profesor' and telefono is null and nif like '%K';
select nombre from asignatura where cuatrimestre = 1 and curso = 3 and id_grado = 7;
select p.apellido1,p.apellido2,p.nombre,d.nombre as 'departamento' from persona p,profesor r,departamento d where p.id = r.id_profesor and r.id_departamento = d.id order by p.apellido1 asc;
select a.nombre,c.anyo_inicio as 'inicio',c.anyo_fin as 'fin' from persona p,asignatura a,curso_escolar c,alumno_se_matricula_asignatura m where p.nif like '26902806M' and p.id = m.id_alumno and m.id_asignatura = a.id and m.id_curso_escolar = c.id;
select distinct d.nombre as 'departamentos' from departamento d,profesor p,asignatura a,grado g where g.nombre like 'Grado en Ingeniería Informática (Plan 2015)' and g.id = a.id_grado and p.id_profesor = a.id_profesor and p.id_departamento = d.id;
select distinct p.apellido1 as 'apellido 1',p.apellido2 as 'apellido 2',p.nombre as 'nombre' from persona p,curso_escolar c,alumno_se_matricula_asignatura a where p.tipo like 'alumno' and p.id = a.id_alumno and a.id_curso_escolar = c.id and c.anyo_inicio = 2018;
select departamento.nombre as 'departamento',persona.apellido1 as 'primer apellido',persona.apellido2 as 'segundo apellido',persona.nombre 'nombre' from persona right outer join profesor on persona.tipo like 'profesor' and persona.id = profesor.id_profesor left outer join departamento on profesor.id_departamento = departamento.id order by departamento.nombre,persona.apellido1,persona.apellido2,persona.nombre asc;
select persona.apellido1 as 'primer apellido',persona.apellido2 as 'segundo apellido',persona.nombre 'nombre' from persona left outer join profesor on persona.tipo like 'profesor' and persona.id = profesor.id_profesor right outer join departamento on profesor.id_departamento = departamento.id where departamento.id is null;
select departamento.nombre as 'departamento' from departamento left join profesor on departamento.id = profesor.id_departamento where profesor.id_profesor is null;
select distinct * from persona where tipo like 'profesor' and not exists (select null from asignatura a where a.id_profesor = persona.id);
select nombre as 'asignatura' from asignatura where id_profesor is null;
select distinct departamento.nombre as 'departamento' from departamento left join profesor on departamento.id = profesor.id_departamento left join asignatura on profesor.id_profesor = asignatura.id_profesor where asignatura.id_profesor is null;
select count(*) as 'Numero alumnos' from persona where persona.tipo like 'alumno';
select count(*) as 'Numero alumnos del 1999' from persona where persona.tipo like 'alumno' and fecha_nacimiento like '1999%';
select departamento.nombre as 'departamento',(select count(*) from profesor where profesor.id_departamento = departamento.id) as 'numero' from departamento having numero != 0 order by numero desc;
select departamento.nombre as 'departamento',(select count(*) from profesor where profesor.id_departamento = departamento.id) as 'numero' from departamento order by numero desc;
select grado.nombre as 'grado',(select count(*) from asignatura where asignatura.id_grado = grado.id) as 'numero' from grado order by numero desc;
select grado.nombre as 'grado',(select count(*) from asignatura where asignatura.id_grado = grado.id) as 'numero' from grado having numero > 40;
--7	select grado.nombre as 'grado',asignatura.tipo as 'tipo',count(asignatura.creditos) from grado join asignatura on grado.id = asignatura.id_grado;
select curso_escolar.anyo_inicio as 'inicio',(select count(*) from alumno_se_matricula_asignatura where alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id) as 'num' from curso_escolar order by num desc;
select persona.id as 'id',persona.apellido1 as 'primer apellido',persona.apellido2 as 'segundo apellido',persona.nombre as 'nombre',(select count(*) from asignatura where asignatura.id_profesor = persona.id) as 'num' from persona where persona.tipo like 'profesor' order by num desc;
select * from persona where tipo like 'alumno' order by fecha_nacimiento desc limit 1;
select distinct id as 'id',apellido1 as 'primer apellido',apellido2 as 'segundo apellido',nombre as 'nomnbre' from persona where tipo like 'profesor' and not exists (select null from asignatura a where a.id_profesor = persona.id);
